
services:
  - type: cron
    name: dhu-notifier
    runtime: python
    schedule: "*/15 * * * *"
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python dhu_notifier.py"
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: TELEGRAM_CHAT_ID
        sync: false
      - key: EMAIL_SENDER
        sync: false
      - key: EMAIL_PASSWORD
        sync: false
      - key: EMAIL_RECEIVER
        sync: false
      - key: SMTP_SERVER
        sync: false
      - key: SMTP_PORT
        sync: false

  - type: cron
    name: saga-notifier
    runtime: python
    schedule: "*/15 * * * *"
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python saga_notifier.py"
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: TELEGRAM_CHAT_ID
        sync: false
      - key: EMAIL_SENDER
        sync: false
      - key: EMAIL_PASSWORD
        sync: false
      - key: EMAIL_RECEIVER
        sync: false
      - key: SMTP_SERVER
        sync: false
      - key: SMTP_PORT
        sync: false
